### ISSUE TITLE
Ext compilation

### ISSUE THREAD

**Issue by MaksymTymkovych** [raphaelsulzer/dgnn#5]
Hello, thank you for your project.
During ext compilation I had an error:
`python utils/setup_libmesh_convonet.py build_ext --inplace`
Here is the output
```
Traceback (most recent call last):
  File "/media/maxim/big-500/dgnn/utils/setup_libmesh_convonet.py", line 88, in <module>
    ext_modules=cythonize(ext_modules),
  File "/media/maxim/big-500/envs/dgnn/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 965, in cythonize
    module_list, module_metadata = create_extension_list(
  File "/media/maxim/big-500/envs/dgnn/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/media/maxim/big-500/envs/dgnn/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
    raise ValueError(error_msg)
ValueError: 'libmesh/triangle_hash.pyx' doesn't match any files
```

To compile it I changed the setup_libmesh_convonet.py file:

```
triangle_hash_module = Extension(
    'utils.libmesh.triangle_hash',
    sources=[
        'utils/libmesh/triangle_hash.pyx'
    ],
    libraries=['m'],  # Unix-like specific
    include_dirs=[numpy_include_dir]
)
```

I don't know how it affects the rest of the project.

**Comment by raphaelsulzer** [comment]
Hi and thanks for the remark.

Libmesh is only really used in evaluation, for fast calculation of volumetric intersection over union between a ground truth and reconstructed mesh.

If it compiled, everything should be fine.
